---
- name: validate states on EOS devices
  hosts: FABRIC
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: validate states on EOS devices
      ansible.builtin.import_role:
         name: arista.avd.eos_validate_state
      vars:
         use_anta: true